apiVersion: apps/v1
kind: Deployment
metadata:
  name: journallab2-db
  labels:
    app: journallab2-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journallab2-db
  template:
    metadata:
      labels:
        app: journallab2-db
    spec:
      containers:
        - name: mysql # Container name
          image: mysql:8 # MySQL image version
          ports:
            - containerPort: 3306 # Expose port 3306
          env:
            - name: MYSQL_ROOT_PASSWORD # Environment variable for MySQL root password
              value: "1234"
            - name: MYSQL_DATABASE # Environment variable for initial database creation
              value: journaldb
          volumeMounts:
            - name: mysql-data # Mount volume for MySQL data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data # Define the volume
          emptyDir: {}

      